"""add_department_keywords_and_sla

Revision ID: 1b34cdcf9be7
Revises: de57b279d9b1
Create Date: 2026-09-03 10:07:09.137147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b34cdcf9be7'
down_revision: Union[str, Sequence[str], None] = 'de57b279d9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('departments', sa.Column('sla_hours', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated_at')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'sla_hours')
    op.drop_column('departments', 'keywords')
    op.drop_column('agents', 'updated_at')
    # ### end Alembic commands ###
