"""enterprise_saas_schema_sync

Revision ID: 888dcd2ef363
Revises: 8de36ca7d737
Create Date: 2026-09-15 18:54:39.280538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888dcd2ef363'
down_revision: Union[str, Sequence[str], None] = '8de36ca7d737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('complaint_feedback', 'field_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'department'::character varying"))
    op.alter_column('complaint_feedback', 'is_category_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('complaint_feedback', 'is_sentiment_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('model_versions_task_name_key'), 'model_versions', type_='unique')
    op.drop_column('model_versions', 'accuracy_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('accuracy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('model_versions_task_name_key'), 'model_versions', ['task_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('complaint_feedback', 'is_sentiment_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('complaint_feedback', 'is_category_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('complaint_feedback', 'field_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'department'::character varying"))
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
