"""add_team_keywords_and_code

Revision ID: a8d3a3c1ce66
Revises: 1b34cdcf9be7
Create Date: 2026-09-03 10:10:21.079427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d3a3c1ce66'
down_revision: Union[str, Sequence[str], None] = '1b34cdcf9be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('lead_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_teams_department_id'), 'teams', ['department_id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_department_id'), table_name='teams')
    op.drop_column('teams', 'lead_name')
    op.drop_column('teams', 'keywords')
    op.drop_column('teams', 'code')
    # ### end Alembic commands ###
